### ISSUE TITLE
ping problem with ipv6 reality on wifi

### ISSUE THREAD

**Issue by vahidabbasi77** [hiddify/hiddify-next#1247]
### Search first

- [X] I searched and no similar issues were found

### What Happened?

در زمان اتصال به وای فای (در اینترنت همراه مشکلی نیست ) در واقع نتورکی که که احتمالا ipv6 را پشتیبانی نمیکنه زمانی که در بین کانفیگ ها ، کانفیگ ریالتی ipv6 وجود داره اپ هیدیفای چه در ویندوز چه در موبایل پینگ سایر کانفیگ ها رو نمیگیره و زیر علامت اتصال (لوگوی هیدیفای) کانکتینگ میمونه و متصل نمیشه

### Minimal Reproducible Example (MRE)

1- لینک اشتراک شامل 
cdn آیپی تمیز و ریالتی ipv6 

2-متصل به وای فای در اینجا پارس آنلاین

3 پینگی نمیدن کانفیگ ها و ضربدر جلوی کانفیگ ها هست 

### Version

2.1.1

### Platform/OS

Windows

### Relevant log output

```shell
13:53:03.363279 - [D] ProxyRepositoryImpl: getting current ip info using [https://api.ip.sb/geoip/]
13:53:12.266115 - [D] PreferencesEntry<bool, bool>: updating preference [started_by_user](bool) to [false]
13:53:12.267811 - [I] ConnectionNotifier: connection status: DISCONNECTING
13:53:12.268615 - [D] FFISingboxService.[ActiveGroupsClient]: stopping
13:53:12.269120 - [D] IpInfoNotifier: disposing
13:53:12.269120 - [D] FFISingboxService: stopping stats command client
13:53:12.269120 - [D] FFISingboxService.watchGroups: stopping
13:53:12.274786 - [D] SystemTrayNotifier: updating system tray
13:53:12.293131 - [I] ConnectionNotifier: connection status: DISCONNECTED
13:53:12.296466 - [D] SystemTrayNotifier: updating system tray
13:54:37.430305 - [D] PreferencesEntry<bool, dynamic>: getting persisted preference [disable_experimental_feature_notice](bool)
13:54:37.430305 - [D] PreferencesEntry<bool, bool>: updating preference [started_by_user](bool) to [true]
13:54:37.431370 - [I] ConnectionRepositoryImpl: config options: {
  "region": "other",
  "block-ads": false,
  "execute-config-as-is": false,
  "log-level": "warn",
  "resolve-destination": false,
  "ipv6-mode": "ipv4_only",
  "remote-dns-address": "udp://1.1.1.1",
  "remote-dns-domain-strategy": "",
  "direct-dns-address": "1.1.1.1",
  "direct-dns-domain-strategy": "",
  "mixed-port": 12334,
  "tproxy-port": 12335,
  "local-dns-port": 16450,
  "tun-implementation": "mixed",
  "mtu": 9000,
  "strict-route": true,
  "connection-test-url": "http://connectivitycheck.gstatic.com/generate_204",
  "url-test-interval": 600,
  "enable-clash-api": true,
  "clash-api-port": 16756,
  "enable-tun": false,
  "enable-tun-service": false,
  "set-system-proxy": true,
  "bypass-lan": false,
  "allow-connection-from-lan": false,
  "enable-fake-dns": false,
  "enable-dns-routing": true,
  "independent-dns-cache": true,
  "rules": [],
  "mux": {
    "enable": false,
    "padding": false,
    "max-streams": 8,
    "protocol": "h2mux"
  },
  "tls-tricks": {
    "enable-fragment": false,
    "fragment-size": "10-30",
    "fragment-sleep": "2-8",
    "mixed-sni-case": false,
    "enable-padding": false,
    "padding-size": "1-1500"
  },
  "warp": {
    "enable": false,
    "mode": "proxy_over_warp",
    "wireguard-config": "",
    "license-key": "",
    "account-id": "",
    "access-token": "",
    "clean-ip": "auto",
    "clean-port": 0,
    "noise": "1-3",
    "noise-size": "10-30",
    "noise-delay": "10-30",
    "noise-mode": "m6"
  },
  "warp2": {
    "enable": false,
    "mode": "proxy_over_warp",
    "wireguard-config": "",
    "license-key": "",
    "account-id": "",
    "access-token": "",
    "clean-ip": "auto",
    "clean-port": 0,
    "noise": "1-3",
    "noise-size": "10-30",
    "noise-delay": "10-30",
    "noise-mode": "m6"
  }
}
Memory Limit: true
13:54:37.432249 - [D] FFISingboxService: starting, memory limit: [true]
13:54:37.432249 - [I] ConnectionNotifier: connection status: CONNECTING
13:54:37.435468 - [D] SystemTrayNotifier: updating system tray
13:54:37.536246 - [I] ConnectionNotifier: connection status: CONNECTED
13:54:37.536763 - [D] IpInfoNotifier: disposing
13:54:37.537305 - [D] ProxyRepositoryImpl: getting current ip info using [https://ipwho.is/]
13:54:37.541574 - [D] SystemTrayNotifier: updating system tray
13:54:39.061627 - [D] ProxyRepositoryImpl: failed getting ip info using [https://ipwho.is/]
FormatException: invalid json
#0      IpInfo.fromIpwhoIsJson (package:hiddify/features/proxy/model/ip_info_entity.dart:115)
#1      ProxyRepositoryImpl.getCurrentIpInfo.<anonymous closure> (package:hiddify/features/proxy/data/proxy_repository.dart:146)
<asynchronous suspension>
#2      new TaskEither.tryCatch.<anonymous closure> (package:fpdart/src/task_either.dart:280)
<asynchronous suspension>
#3      TaskEither.getOrElse.<anonymous closure> (package:fpdart/src/task_either.dart:161)
<asynchronous suspension>
#4      IpInfoNotifier.build (package:hiddify/features/proxy/active/active_proxy_notifier.dart:48)
<asynchronous suspension>
#5      FutureHandlerProviderElementMixin.handleFuture.<anonymous closure>.<anonymous closure> (package:riverpod/src/async_notifier/base.dart:348)
<asynchronous suspension>

13:54:39.061627 - [D] ProxyRepositoryImpl: getting current ip info using [https://api.ip.sb/geoip/]
13:54:40.882318 - [D] ProxiesOverviewNotifier: testing group: [select]
13:54:40.882318 - [D] ProxyRepositoryImpl: testing group: [select]
13:54:40.882318 - [W] ProxyRepositoryImpl: only auto proxy group can do url test. Please change go code if you want
13:54:43.154422 - [D] ProxiesOverviewNotifier: testing group: [select]
13:54:43.154422 - [D] ProxyRepositoryImpl: testing group: [select]
13:54:43.154422 - [W] ProxyRepositoryImpl: only auto proxy group can do url test. Please change go code if you want
13:54:49.800440 - [D] IpInfoNotifier: entering idle mode
13:54:49.800440 - [D] IpInfoNotifier: disposing
```

### Are you willing to submit a PR? If you know how to fix the bug.

- [ ] I'm willing to submit a PR (Thank you!)

**Comment by elyasneo** [comment]
من هم همین مشکل رو دارم 
دقیقا روی نت خونگی بعد ی مدت اتصال قطع میشه و نیازه که ی بار قطع و وصل کنم 
بعد از نسخه ۲ این مشکل به وجود اومده و بین کانفیگ ها هم کانفیک ای پی ورژن ۶ هم هست
 بیشتر این مشکل برای کانفیگ هایی هست که با دامنه دارن کار میکنن و کانفیگ هایی ک ایپی مستقیم دارن اکی هستن
