### ISSUE TITLE
خطا در زمان اضافه کردن پروفایل

### ISSUE THREAD

**Issue by omidshojaee** [hiddify/hiddify-next#815]
### Search first

- [X] I searched and no similar issues were found

### What Happened?

زمان ادد کردن پروفایل از طریق کلیپ‌بورد (لینک سابسکریپشن) خطای زیر بروز می‌کنه:

![image](https://github.com/hiddify/hiddify-next/assets/31741561/424fb750-ccfe-40fd-bd15-e1533be7724e)

و تو لاگ این وضعیت دیده میشه:

```
19:08:52.706764 - [D] AddProfile: adding profile, url: [حذف شد]
19:09:09.104180 - [W] ProfileRepositoryImpl: error adding profile by url
DioException [unknown]: null
Error: HandshakeException: Handshake error in client (OS Error: 
	CERTIFICATE_VERIFY_FAILED: unable to get local issuer certificate(../../third_party/boringssl/src/ssl/handshake.cc:393))
#0      DioMixin.fetch.<anonymous closure> (package:dio/src/dio_mixin.dart:510)
#1      _FutureListener.handleError (dart:async/future_impl.dart:180)
#2      Future._propagateToListeners.handleError (dart:async/future_impl.dart:850)
#3      Future._propagateToListeners (dart:async/future_impl.dart:871)
#4      Future._completeError (dart:async/future_impl.dart:651)
#5      _SyncCompleter._completeError (dart:async/future_impl.dart:63)
#6      _Completer.completeError (dart:async/future_impl.dart:27)
#7      Future.any.onError (dart:async/future.dart:613)
#8      _RootZone.runBinary (dart:async/zone.dart:1666)
#9      _FutureListener.handleError (dart:async/future_impl.dart:177)
#10     Future._propagateToListeners.handleError (dart:async/future_impl.dart:850)
#11     Future._propagateToListeners (dart:async/future_impl.dart:871)
#12     Future._completeError (dart:async/future_impl.dart:651)
#13     Future._chainForeignFuture.<anonymous closure> (dart:async/future_impl.dart:556)
#14     _microtaskLoop (dart:async/schedule_microtask.dart:40)
#15     _startMicrotaskLoop (dart:async/schedule_microtask.dart:49)

19:09:09.104180 - [W] AddProfile: failed to add profile
ProfileFailure.unexpected(error: DioException [unknown]: null
Error: HandshakeException: Handshake error in client (OS Error: 
	CERTIFICATE_VERIFY_FAILED: unable to get local issuer certificate(../../third_party/boringssl/src/ssl/handshake.cc:393)), stackTrace: #0      DioMixin.fetch.<anonymous closure> (package:dio/src/dio_mixin.dart:510)
#1      _FutureListener.handleError (dart:async/future_impl.dart:180)
#2      Future._propagateToListeners.handleError (dart:async/future_impl.dart:850)
#3      Future._propagateToListeners (dart:async/future_impl.dart:871)
#4      Future._completeError (dart:async/future_impl.dart:651)
#5      _SyncCompleter._completeError (dart:async/future_impl.dart:63)
#6      _Completer.completeError (dart:async/future_impl.dart:27)
#7      Future.any.onError (dart:async/future.dart:613)
#8      _RootZone.runBinary (dart:async/zone.dart:1666)
#9      _FutureListener.handleError (dart:async/future_impl.dart:177)
#10     Future._propagateToListeners.handleError (dart:async/future_impl.dart:850)
#11     Future._propagateToListeners (dart:async/future_impl.dart:871)
#12     Future._completeError (dart:async/future_impl.dart:651)
#13     Future._chainForeignFuture.<anonymous closure> (dart:async/future_impl.dart:556)
#14     _microtaskLoop (dart:async/schedule_microtask.dart:40)
#15     _startMicrotaskLoop (dart:async/schedule_microtask.dart:49)
)
```

### Minimal Reproducible Example (MRE)

سرور من هیدیفای منیجر نسخه 10.10.20 هست. سیستم عامل ویندوز 11. کلاینت هم 1.1.1.

### Version

1.1.1

### Platform/OS

Windows

### Are you willing to submit a PR? If you know how to fix the bug.

- [ ] I'm willing to submit a PR (Thank you!)

**Comment by caribbeansyrup** [comment]
I have the same problem

**Comment by lymanjre** [comment]
احتمال دارد دامنه یا آیپی اختلال داشته باشد

**Comment by omidshojaee** [comment]
د ر اینصورت v2rayN هم نباید بتونه ساب رو ایمپورت کنه ولی مشکلی نداره. ضمنا ایمپورت کردن کانفیگ از همون ساب هم انجام میشه ولی ساب ایمپورت نمیشه.

**Comment by omidshojaee** [comment]
مشکل من بعد از نصب آپدیت KB5036980 و ریستارت سیستم حل شد
